### ISSUE TITLE
Wrapped java.lang.IllegalAccessException

### ISSUE THREAD

**Issue by ekjuanrejon** [nextgenhealthcare/connect-docker#43]
Hello having the following

`
DETAILS:	Wrapped java.lang.IllegalAccessException: class org.mozilla.javascript.MemberBox cannot access class sun.net.www.protocol.http.HttpURLConnection (in module java.base) because module java.base does not export sun.net.www.protocol.http to unnamed module @5990e6c5
	at fba48cf7-a115-4a0c-975b-89020dc2aa7c_JavaScript_Filter_Transformer_0:213 (doTransform)
	at fba48cf7-a115-4a0c-975b-89020dc2aa7c_JavaScript_Filter_Transformer_0:1003 (doScript)
	at fba48cf7-a115-4a0c-975b-89020dc2aa7c_JavaScript_Filter_Transformer_0:1005
	at com.mirth.connect.server.transformers.JavaScriptFilterTransformer$FilterTransformerTask.doCall(JavaScriptFilterTransformer.java:235)
	at com.mirth.connect.server.transformers.JavaScriptFilterTransformer$FilterTransformerTask.doCall(JavaScriptFilterTransformer.java:187)
	at com.mirth.connect.server.util.javascript.JavaScriptTask.call(JavaScriptTask.java:114)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

any ideas

**Comment by pladesma** [comment]
Can you provide some more information including the Mirth Connect version, the Docker image tag, and steps to reproduce the issue?
